sudo: required
language: go
deploy:
  provider: gae
  project: pulsecheck-167520
  keyfile: gce.json
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_6951afb58799_key -iv $encrypted_6951afb58799_iv
  -in gce.json.enc -out gce.json -d
